sudo: required

services:
  - docker

language: java

jdk:
  - oraclejdk8
  - oraclejdk9

script:
  - docker --version
  - docker-compose --version
  - cd dev/
  - mvn clean verify
  - mvn install -Dmaven.javadoc.skip=true -B -V
